version: '2.2'
services:

  zabbix:
    container_name: zabbix
    image: zabbix/zabbix-server-mysql # Se debe especificar la imagen completa, como la de la aplicación Zabbix
    restart: always
    volumes:
      - /volums/moodle_project/zabbix:/var/lib/zabbix
    env_file:
      - zabbix.env
    networks:
      - xarxa_bridge
    ports:
      - "5756:8080"

networks:
  xarxa_bridge:
    name: xarxa_bridge
    driver: bridge
  internal:
    name: internal
