services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - moodle_network
    restart: always
  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=mentefria69
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=MoodleSite
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8443
      - PHP_MEMORY_LIMIT=512M
      - DB_WAIT_TIME=120
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - apache_conf:/bitnami/apache/conf
    depends_on:
      - mariadb
    networks:
      - moodle_network
    restart: always

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
  apache_conf:

networks:
  moodle_network: