services:
  wireguard:
    image: linuxserver/wireguard
    container_name: vpn-dmz-wg
    # PERMISIONS
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # SET VARIABLES
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=172.30.10.13
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.8.0.0
      - ALLOWEDIPS=192.168.20.0/24
    volumes:
      - /volums/docker-wireguard-vpn-dmz/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped